### ISSUE TITLE
Firebase korrekt anwenden

### ISSUE THREAD

**Issue by sarner** [riesendaniel/myFinanceTracker#37]
Prüfen, ob die Möglichkeiten von Firebase (Datenbank, Authentifizierung, Hosting) korrekt verwendet werden.

**Comment by riesendaniel** [comment]
-> Authorisierung, Strukturierung der Daten

**Comment by riesendaniel** [comment]
- Passwort vergessen

**Comment by riesendaniel** [comment]
@sarner Passwort vergessen ist bereits mit dem Email Modul drin, wenn man eine bestehende Email angibt beim Login kommt unten das Feld Trouble signing in? und kann sich so das Passwort zukommen lassen. Somit würde ich die Story abschliessen, ist das für dich in Ordnung?

**Comment by sarner** [comment]
Wenn das so ist, passt das natürlich!
