### ISSUE TITLE
Finetuning Modul Ausgaben

### ISSUE THREAD

**Issue by riesendaniel** [riesendaniel/myFinanceTracker#42]
Filter / sortieren
Editieren / löschen von Einträgen
Gruppe aus Allgemeinem Reducer

**Comment by sarner** [comment]
Verbesserungen aus den Benutzertests:
- [x] Standarddatum heute
- [x] Vorauswahl einer Kategorie
- [x] Abbrechen Button

**Comment by riesendaniel** [comment]
#59
