### ISSUE TITLE
Präsentation vorbereiten

### ISSUE THREAD

**Issue by sarner** [riesendaniel/myFinanceTracker#57]

**Comment by sarner** [comment]
Präsentations-Ablauf
- 7min Präsentation
- 3min Fragen
- 2min Umbau

Inhalt der Präsentation:
- Thema kurz (!) erläutern.
- Auf folgende Punkte eingehen:
  - Besonders gut gelöst?
  - Was würden wir anders machen?
  - Was haben wir gelernt?
- Kurze Demo der realisierten App

**Comment by riesendaniel** [comment]
- Grafik Tools
- Rückblick
- Namen und Datum ergänzen

**Comment by riesendaniel** [comment]
@sarner: Ich habe mal die Präsentation überarbeitet. Hast du noch ergänzungen oder ist es für dich so in Ordnung?

**Comment by sarner** [comment]
Super, passt so für mich!
Wir müssen uns dann nur noch einigen, wer welchen Teil übernimmt.

**Comment by riesendaniel** [comment]
Ich könnte den Start machen:
- Begrüssung und Inhalt (1 min)
- Was ist myFinanceTracker (1 min)
- Tools und Frameworks (2 min)

und du:
- Rückblick (1 min)
- Was haben wir gelernt (2 min)
- Demo 

Wäre das ok für dich?

Ohne Demo wäre es so ca. 7 min. Gehört die Demo auch in diese Zeit? Sonst müssen wir noch etwas kürzen.

**Comment by sarner** [comment]
Für mich ist die Aufteilung so in Ordnung.
Ich gehe davon aus, dass die Demo zu den 7 Minuten zählt. Beide halten ihre Teile etwas kürzer und dann passt es :-)
