### ISSUE TITLE
Benutzertest

### ISSUE THREAD

**Issue by sarner** [riesendaniel/myFinanceTracker#8]
Benutzertest am Prototypen durchführen

**Comment by sarner** [comment]
Rückmeldungen aus dem UI Test am Prototypen (4d95989e2b26da98cc2a82d708bd8130d1c0e95a):

**allgemein**
- Das Logo soll als Link zur Home-Seite dienen.

**Registration**
- [mobile] Alle Input-Felder auf einer Seite belassen und ggf. den Benutzernamen weglassen.

**Menü**
- Den Link zur Übersicht an oberster Stelle führen.
- Kann der Link zu den Einstellungen entfernt werden?

**Filter**
- [mobile] Die Filter-Felder müssen optional sein (d.h. kein Input bedeutet kein Filter).
- Für den Betrag soll auch die Variante "zwischen" angeboten werden.
- Filter werden mit "AND" kombiniert.

**Einkommen**
- Bis jetzt ist nur ein Einkommen (Lohn) vorgesehen. Ggf. könnte dies erweitert werden, um das Erfassen mehrerer Einkommen zu erlauben.
- Wie werden einmalige Einkommen erfasst?

**Übersicht**
- [Desktop] Kein Link "weitere Ausgaben", da jeweils die Karte angeklickt werden kann.
- Verfügbares Restbudget
- Vergleiche der Ausgaben vergangener Monate (pro Kategorie)
- ...

Anschliessend müssen die Mockups angepasst werden.

**Comment by sarner** [comment]
@riesendaniel Was meinst du zu den Rückmeldungen?

**Comment by riesendaniel** [comment]
Output soll im Wiki dokumentiert werden und allefällige Issues erfasst werden

**Comment by riesendaniel** [comment]
**Budget**
- Es ist nicht ganz klar was die Beträge innerhalb der Kategorie sollen, am besten mit Beschriftungen ergänzen.
- Hauptkategorie hinzufügen sollte ein Button sein, oder anderst dargestellt werden, so ist es nicht ganz klar.

**Dashboard**
- Sind die Diagramme auf dem Mobile lesbar? Inklusive Beschriftungen und Legende, war auf dem Mockup schwierig zu erkennen.

**Ausgaben**
- Es sollte viel einfacher sein eine neue Ausgabe zu erfassen, mit wenigen klickts. Vielleicht direkt über der Liste (vielleicht Tagesdatum / Meist genutzte Kategorie vorabgefüllt) 
Anmerkung von mir: Es muss möglich sein ohne Login neue Ausgaben zu erfassen.
- [Mobile] Neue Ausgabe erfassen auf einem Screen, ohne detail button. Abbrechen button fehlt.

**Allgemein**
- Mehrere Personen ermöglichen. Wenn mehrere Personen in einen Haushalt leben.

**Registrierung**
- [Mobile] Ist kompliziert über 2 Seiten, es sind nicht viel Felder, daher kann man dies auf einer Seite darstellen.

**Lohn**
- AHV Abzug - Prozentzahl noch anzeigen, einfach damit es vollständig ist.

Ich habe mein Benutzertest auch durchgeführt, was meinst du zu diesen Punkten?

**Comment by riesendaniel** [comment]
@sarner: Besprechen wir sonst am nächsten mal zu welchen Punkten wir einen Issue erfassen und einplanen.

**Comment by sarner** [comment]
Finde ich gut. Wir können uns von mir aus auch noch überlegen, ob wir uns dann etwas früher treffen...

**Comment by riesendaniel** [comment]
Ja ich denke das macht Sinn.

**Comment by sarner** [comment]
Output aus der Besprechung im Wiki dokumentieren

**Comment by sarner** [comment]
Wiki angepasst
