### ISSUE TITLE
Projekt abgeben

### ISSUE THREAD

**Issue by sarner** [riesendaniel/myFinanceTracker#91]
Vorgängig nochmals das Projekt von leer aufsetzen, um die Informationen zu testen!

- Link zum Source-Repository.
- Namen des Branchs (nicht master).
- Link zum Live-Server.

- Zugangsdaten der vorhandenen User:
  - admin@myfinancetracker.ch
  - user@myfinancetracker.ch
  - anonym@myfinancetracker.ch
- ReadMe bzw. Setup-Anleitung direkt im Mail oder im Repository.
  - Inhalte von .env.local
  - npm install
  - npm run start für lokale Entwicklungsumgebung
  - npm test, npm e2e-test für Tests
- Besondere Leistungen bitte direkt im ReadMe/Mail erwähnen.
  - UseCases, Mockups, Usertests mit den Mockups -> Link zu Wiki und Ordner doc/
  - responsive Tabelle
  - Styleguides von AirBnB
  - Einbindung von Travis
  - e2e
  - Datenintegrität & Security mit Regeln in firestore
  - ...

**Comment by sarner** [comment]
Ich habe das Projekt nochmals neu aufgesetzt und vorgängig alle globalen Installationen gelöscht. Bei mir hat noch alles funktioniert.

**Comment by riesendaniel** [comment]
bei mir hat fast alles funktioniert.
ich habe nach dem starten einige console Fehler erhalten, hast du diese auch?
Warning: Failed prop type: The prop `breakpoint` is marked as required in `ResponsiveTableCell`, but its value is `undefined`.
    in ResponsiveTableCell (at DashboardComponent.jsx:253)

Zudem liefert npm run lint noch einen Fehler:
C:\Users\Daniel\git\myFinanceTracker\src\components\Logout.jsx
  21:32  error  Block must not be padded by blank lines  padded-blocks

Ich habe eslint aktuell wieder aus dem Travis build rausgenommen. Da es nicht funktioniert.

Ich Schaue morgen mal ob ich noch dazu komme, um diese Punkte noch anzuschauen.

Wollen wir beim env.local noch erwähnen wo das File erstellt werden muss? also im root verzeichnis vom projekt, oder ist das selbsterklärend?

**Comment by sarner** [comment]
> bei mir hat fast alles funktioniert.

Sehr gut!

> Warning: Failed prop type: The prop `breakpoint` is marked as required in `ResponsiveTableCell`, but its value is `undefined`.
> in ResponsiveTableCell (at DashboardComponent.jsx:253)

Stimmt, der (und andere) taucht bei mir auch auf. Ist nun geflickt.

> Zudem liefert npm run lint noch einen Fehler:
> C:\Users\Daniel\git\myFinanceTracker\src\components\Logout.jsx
> 21:32 error Block must not be padded by blank lines padded-blocks

Danke für's Fixen.

> Ich habe eslint aktuell wieder aus dem Travis build rausgenommen. Da es nicht funktioniert.
> Ich Schaue morgen mal ob ich noch dazu komme, um diese Punkte noch anzuschauen.

Von mir aus können wir es auch gut weglassen.

> Wollen wir beim env.local noch erwähnen wo das File erstellt werden muss? also im root verzeichnis vom projekt, oder ist das selbsterklärend?

Guter Hinweis. Habe ich noch ergänzt.
